### ISSUE TITLE
Restore backup configuration

### ISSUE THREAD

**Issue by pickeld** [notoriousbdg/hassio-addons#1]
hey, first i want to say thank you for you hard work,
i just installed your addon and i dont want to configure all the devices again, is it possible to upload a ".bk" file to the backup folder? 
thank you

**Comment by pickeld** [comment]
i just came up with another issue, did you exposed the port on which habridge sends the pairing command? i can't get it to pair

**Comment by notoriousbdg** [comment]
I can update the add-on to map the share folder to /share.  You could then upload your backup to a folder on the share share over samba then restore it from /share folder.  I'll check in that change tomorrow.

Can you clarify what you mean by pair?

**Comment by pickeld** [comment]
Hey. Mapping theshare folder will be great. Thanks.

Pairing is the ability to pair the habridge with the Google home app. (Adding the Philips Hue Account)

One more thing. Since im using SSL in my hass configuration im nkt able to  add the iframe panel. 
You cant surf to a non SSL page if u r using ssl in hass. 
Is ot possible to map the ssl folder as well and run the habridge withh ssl certificates?
 Much appreciated
David

**Comment by pickeld** [comment]
Same ssl request for the node red addon

**Comment by notoriousbdg** [comment]
I've updated the HA Bridge add-on to fix the discovery issue with Alexa.  It was already working for me with Google Home.  To fix the Alexa issue, I had to add a configuration parameter for the server IP, which needs to be set to the IP of your hass.io machine.

I also migrated the config to /share/habridge since backups can only use relative paths.  It should automatically move your existing config from /data to /share/habridge for you.

Lastly, I don't see a way to configure SSL for HA Bridge, so it looks like you'll need to setup a separate reverse proxy to overcome that issue.

**Comment by pickeld** [comment]
@notoriousbdg that was fast! great job! thank you very much

what kind of proxy to you recommend to use for the ssl issue?
are you looking for more nice addons ideas? ;) 

have a great day

**Comment by notoriousbdg** [comment]
There are 2 nginx add-ons available (that I know of).  The first one is the built-in one (https://home-assistant.io/addons/nginx_proxy/), but it doesn't appear to have a way to add additional ports.  The second one is https://github.com/bestlibre/hassio-addons/tree/master/nginx_proxy might work, which looks like it might work if you create a separate hostname and cert for HA Proxy.

I haven't tried either of them yet, so I can't say for sure that they work for this use case.
